server:
  Port: 5005
  RunMode: debug
logger:
  filePath: ../logs/logs.log
  Encoding: json
  level: debug
  logger: zap

cors:
  allowOrigin: "*"
postgres:
  host: postgres_container
  port: 5432
  user: postgres
  password: admin
  dbName: car_sale_db
  sslMode: disable
  maxIdleConns: 15
  maxOpenConns: 100
  connMaxLifetime: 5

redis:
 host: redis_container
 port: 6379
 password: 
 db: 0
 readTimeout: 10
 writeTimeout: 10
 dialTimeout: 10
 minIdleConnections: 100
 poolSize: 10
 poolTimeout: 15
 idleCheckFrequency: 500
 passwrd:
  includeChars: true
  includeDigits: true
  minLength: 6
  maxLength: 64
  includeUppercase: true
  includeLowercase: true
